### ISSUE TITLE
[config] remove "project"; add "name" and "description"

### ISSUE THREAD

**Issue by boite** [droid-php/droid#19]
The top-level config directive `project` is unused. It is also confusing because its name suggests that other directives (e.g. `targets`) should be nested beneath it.

Let's kill it and add the top-level directives `name` and `description`:-
- add Project.name and Project.description to droid-model
- parse the directives and set the Project properties, in YamlLoader
- display the name and description in the output of the `config` command

**Comment by joostfaassen** [comment]
👍 makes total sense
