### ISSUE TITLE
[config] why the "register" directive?

### ISSUE THREAD

**Issue by boite** [droid-php/droid#20]
This directive is used to add commands to droid. The value should be a mapping of ClassName to Properties. A "name" property is used to name the command, if present. No other properties are used.

The command is added to the droid app simply by instantiating ClassName. So this feature cannot work for a command if it needs dependencies to be injected through its constructor.

Is there any benefit to this feature, given that droid has a plugin mechanism by which commands may be registered?

**Comment by joostfaassen** [comment]
This feature was here to register regular symfony commands. In practice this was never used, as the plugin mechanism works fine. I'd be fine /w having this legacy functionality removed.
