### ISSUE TITLE
Module naming

### ISSUE THREAD

**Issue by boite** [droid-php/droid#21]
Although a Module's droid.yml has a `project.name`, the name is meaningless.  A module's name is whatever name is given to it in a droid project that uses it: a module can be named whatever you want.

This is somewhat confusing, but it greatly simplifies the code dealing with installation and use of modules.

Also, the top-level directive `project` is less than intuitive (because it's a module, not a project).

Therefore it would be a good idea to:-
- kill `project.name`
- replace `project.description` with `description`
- document that the name is simply that which you will refer to it in your project (i.e. anything, as long as it's consistently used within a particular project)

**Comment by joostfaassen** [comment]
agreed!
