### ISSUE TITLE
Socket used by droid to connect to Inventory hosts

### ISSUE THREAD

**Issue by boite** [droid-php/droid#22]
A droid-model Host has these properties:-
- `public_ip`
- `public_port`
- `private_ip`
- `private_port`

Additionally there are synonyms for the `public_ip` {g,s}etter:
- `getConnectionIp`
- `setConnectionIp`

Having private and public ports is useful. The other properties and methods are confusing: `*_port` are used only to determine which port droid should use to connect; and droid only ever uses `public_*`.

We should do this instead:-
- `public_ip`
- `private_ip`
- `droid_ip`
- `droid_port # default: 22`

`droid_port` could also be named `ssh_port` (because droid only speaks ssh), but `droid_port` is clearer about the purpose (it's the port used by droid).

We should decide whether the expected value of `droid_ip` is an IP address or a string: `public` or `private`. My preference is an address: users can use a Yaml anchor if they don't want the redundancy of declaring an IP address in two places; a magic string is less than intuitive; and it would be possible to set `droid_ip` to an address that is neither `public_ip` or `private_ip`.

A valid Inventory host config is then, at minimum:-

```
hosts:
  some-hostname:
    droid_ip: "203.0.113.1"
```

and for backward compatibility we should also allow:

```
hosts:
  some-hostname:
    public_ip: "203.0.113.1"
```

**Comment by joostfaassen** [comment]
introducing `droid_ip` + `droid_port`, and dropping `public_port` and `private_port` is an excellent idea.

I'll assume we can leave `droid_port` undefined, having it default to 22.

As we'd most likely be defining public_ip and private_ip, having to define `droid_ip` would indeed introduce redundancy. 

What do you think about having ->getDroidIp() work as follows:

```
if $this.droid_ip is defined, return it
if $environment.default_droid_ip==`public` return $this.public_ip
if $environment.default_droid_ip==`private` return $this.private_ip
```

This would allow us to run the same droid project from a laptop, external to the dc, using public ip's. $environment.default_droid_ip would default to `public`.

Once the project is solid, it'd be moved to a control server in the infra, where we set $environment.default_droid_ip to `private`. So it can be used from within the infra's network unchanged.

That's what i had envisioned for getConnectionIp, but I agree it could use a bit more thought..

I'm not sure how $environment.default_droid_ip would be defined.. an environment variable (meh), or as part of the variables.yml file?

**Comment by boite** [comment]
Good idea.

I think `default_droid_ip` should be a droid variable in preference to an environment variable.  The only downside might be when you set the value to `private` on the control server and then later git pull the project and overwrite it, but this might be easy to solve by checking in a `env.yml.dist` to the project and using a site-specific `env.yml` on the control server (à la symfony's parameters.yml.dist).

Even better than using a magic variable might be to have a new top-level directive, such as `environment` under which to store these kinds of values. This would be easier to document and perhaps more intuitive.
